/*
 * CubeMX-generated peripheral initialization bodies are intentionally kept in
 * their normal generated files. Preserve the USER CODE sections when
 * regenerating this file.
 */
#include "main.h"
#include "cmsis_os2.h"
#include "freertos.h"
#include "surge_rtos.h"

void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_DMA_Init(void);
void MX_SPI2_Init(void);
void MX_USART1_UART_Init(void);
void MX_USART2_UART_Init(void);
void MX_USART3_UART_Init(void);
void MX_USB_DEVICE_Init(void);

int main(void)
{
    /* Reset peripherals, initialize Flash interface and HAL timebase (TIM6). */
    HAL_Init();
    SystemClock_Config();

    /* GPIO and DMA must precede peripherals which use DMA or chip-select pins. */
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_SPI2_Init();
    MX_USART1_UART_Init();
    MX_USART2_UART_Init();
    MX_USART3_UART_Init();
    MX_USB_DEVICE_Init();

    /*
     * Read configuration and arm UART DMA before the scheduler starts. This
     * function must not call an RTOS blocking API because the kernel is not
     * running yet.
     */
    Surge_AppHardwareStart();

    /* CMSIS-RTOS2 startup order: initialize kernel, create objects, start. */
    if (osKernelInitialize() != osOK) {
        Error_Handler();
    }
    MX_FREERTOS_Init();
    if (osKernelStart() != osOK) {
        Error_Handler();
    }

    /* A successful osKernelStart() never returns. */
    Error_Handler();
    return 0;
}

/*
 * SystemClock_Config() and MX_*_Init() definitions are generated by CubeMX in
 * the project peripheral source files. The declarations above make the call
 * order explicit without inventing board oscillator data.
 */
