namespace MeasurementMonitor;

partial class MeasurementPanel
{
    private System.ComponentModel.IContainer? components;
    private GroupBox measurementGroup = null!;
    private TableLayoutPanel grid = null!;
    private Label referenceLabel = null!;
    private Label offsetLabel = null!;
    private Label resistanceLabel = null!;
    private Label intervalLabel = null!;
    private Label rs485OnlyLabel = null!;
    private Label resetIntervalLabel = null!;
    private NumericUpDown reference = null!;
    private NumericUpDown offset = null!;
    private NumericUpDown resistance = null!;
    private NumericUpDown interval = null!;
    private ComboBox rs485Only = null!;
    private NumericUpDown resetInterval = null!;
    private ComboBox resetUnit = null!;
    private Button resetReadButton = null!;
    private Button resetWriteButton = null!;
    private Button readButton = null!;
    private Button writeButton = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        measurementGroup = new GroupBox();
        grid = new TableLayoutPanel();
        referenceLabel = new Label();
        offsetLabel = new Label();
        resistanceLabel = new Label();
        intervalLabel = new Label();
        rs485OnlyLabel = new Label();
        resetIntervalLabel = new Label();
        reference = new NumericUpDown();
        offset = new NumericUpDown();
        resistance = new NumericUpDown();
        interval = new NumericUpDown();
        rs485Only = new ComboBox();
        resetInterval = new NumericUpDown();
        resetUnit = new ComboBox();
        resetReadButton = new Button();
        resetWriteButton = new Button();
        readButton = new Button();
        writeButton = new Button();
        ((System.ComponentModel.ISupportInitialize)reference).BeginInit();
        ((System.ComponentModel.ISupportInitialize)offset).BeginInit();
        ((System.ComponentModel.ISupportInitialize)resistance).BeginInit();
        ((System.ComponentModel.ISupportInitialize)interval).BeginInit();
        ((System.ComponentModel.ISupportInitialize)resetInterval).BeginInit();
        measurementGroup.SuspendLayout();
        grid.SuspendLayout();
        SuspendLayout();

        measurementGroup.Controls.Add(grid);
        measurementGroup.Dock = DockStyle.Fill;
        measurementGroup.Name = "measurementGroup";
        measurementGroup.Padding = new Padding(10);
        measurementGroup.TabIndex = 0;
        measurementGroup.TabStop = false;
        measurementGroup.Text = "Measurement 설정";

        grid.ColumnCount = 4;
        grid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120F));
        grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        grid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        grid.Controls.Add(referenceLabel, 0, 0);
        grid.Controls.Add(reference, 1, 0);
        grid.Controls.Add(offsetLabel, 2, 0);
        grid.Controls.Add(offset, 3, 0);
        grid.Controls.Add(resistanceLabel, 0, 1);
        grid.Controls.Add(resistance, 1, 1);
        grid.Controls.Add(intervalLabel, 2, 1);
        grid.Controls.Add(interval, 3, 1);
        grid.Controls.Add(rs485OnlyLabel, 0, 2);
        grid.Controls.Add(rs485Only, 1, 2);
        grid.Controls.Add(resetIntervalLabel, 0, 3);
        grid.Controls.Add(resetInterval, 1, 3);
        grid.Controls.Add(resetUnit, 2, 3);
        grid.Controls.Add(resetReadButton, 1, 4);
        grid.Controls.Add(resetWriteButton, 2, 4);
        grid.Controls.Add(readButton, 1, 5);
        grid.Controls.Add(writeButton, 2, 5);
        grid.Dock = DockStyle.Fill;
        grid.Name = "grid";
        grid.RowCount = 6;
        grid.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        grid.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        grid.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        grid.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        grid.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        grid.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        grid.TabIndex = 0;

        referenceLabel.Anchor = AnchorStyles.Left;
        referenceLabel.AutoSize = true;
        referenceLabel.Name = "referenceLabel";
        referenceLabel.Text = "Reference (mV)";
        offsetLabel.Anchor = AnchorStyles.Left;
        offsetLabel.AutoSize = true;
        offsetLabel.Name = "offsetLabel";
        offsetLabel.Text = "Offset (mV)";
        resistanceLabel.Anchor = AnchorStyles.Left;
        resistanceLabel.AutoSize = true;
        resistanceLabel.Name = "resistanceLabel";
        resistanceLabel.Text = "Resistance (mΩ)";
        intervalLabel.Anchor = AnchorStyles.Left;
        intervalLabel.AutoSize = true;
        intervalLabel.Name = "intervalLabel";
        intervalLabel.Text = "Interval Time (sec)";
        rs485OnlyLabel.Anchor = AnchorStyles.Left;
        rs485OnlyLabel.AutoSize = true;
        rs485OnlyLabel.Name = "rs485OnlyLabel";
        rs485OnlyLabel.Text = "RS485_ONLY";
        resetIntervalLabel.Anchor = AnchorStyles.Left;
        resetIntervalLabel.AutoSize = true;
        resetIntervalLabel.Name = "resetIntervalLabel";
        resetIntervalLabel.Text = "RTC Reset Period";

        reference.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        reference.DecimalPlaces = 1;
        reference.Maximum = 1000000M;
        reference.Name = "reference";
        reference.ThousandsSeparator = true;
        offset.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        offset.DecimalPlaces = 1;
        offset.Maximum = 1000000M;
        offset.Minimum = -1000000M;
        offset.Name = "offset";
        offset.ThousandsSeparator = true;
        resistance.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        resistance.DecimalPlaces = 3;
        resistance.Maximum = 100000000M;
        resistance.Name = "resistance";
        resistance.ThousandsSeparator = true;
        interval.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        interval.DecimalPlaces = 3;
        interval.Maximum = 86400M;
        interval.Minimum = 0.001M;
        interval.Name = "interval";
        interval.ThousandsSeparator = true;
        interval.Value = 1M;
        resetInterval.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        resetInterval.DecimalPlaces = 3;
        resetInterval.Maximum = 525600M;
        resetInterval.Name = "resetInterval";
        resetInterval.ThousandsSeparator = true;
        resetUnit.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        resetUnit.DropDownStyle = ComboBoxStyle.DropDownList;
        resetUnit.Items.AddRange(new object[] { "Minutes", "Hours" });
        resetUnit.Name = "resetUnit";
        resetUnit.SelectedIndex = 0;

        rs485Only.Anchor = AnchorStyles.Left | AnchorStyles.Right;
        rs485Only.DropDownStyle = ComboBoxStyle.DropDownList;
        rs485Only.Items.AddRange(new object[] { "OFF", "ON" });
        rs485Only.Name = "rs485Only";
        rs485Only.SelectedIndex = 0;
        rs485Only.TabIndex = 4;

        resetReadButton.Anchor = AnchorStyles.None;
        resetReadButton.AutoSize = false;
        resetReadButton.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
        resetReadButton.Name = "resetReadButton";
        resetReadButton.Size = new Size(90, 32);
        resetReadButton.TabIndex = 5;
        resetReadButton.Text = "Reset Read";
        resetReadButton.UseVisualStyleBackColor = true;
        resetWriteButton.Anchor = AnchorStyles.None;
        resetWriteButton.AutoSize = false;
        resetWriteButton.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
        resetWriteButton.Name = "resetWriteButton";
        resetWriteButton.Size = new Size(90, 32);
        resetWriteButton.TabIndex = 6;
        resetWriteButton.Text = "Reset Write";
        resetWriteButton.UseVisualStyleBackColor = true;
        readButton.Anchor = AnchorStyles.None;
        readButton.AutoSize = false;
        readButton.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
        readButton.Name = "readButton";
        readButton.Size = new Size(90, 32);
        readButton.TabIndex = 7;
        readButton.Text = "Read";
        readButton.UseVisualStyleBackColor = true;
        writeButton.Anchor = AnchorStyles.None;
        writeButton.AutoSize = false;
        writeButton.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
        writeButton.Name = "writeButton";
        writeButton.Size = new Size(90, 32);
        writeButton.TabIndex = 8;
        writeButton.Text = "Write";
        writeButton.UseVisualStyleBackColor = true;

        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        Controls.Add(measurementGroup);
        MinimumSize = new Size(440, 210);
        Name = "MeasurementPanel";
        Size = new Size(520, 230);
        ((System.ComponentModel.ISupportInitialize)reference).EndInit();
        ((System.ComponentModel.ISupportInitialize)offset).EndInit();
        ((System.ComponentModel.ISupportInitialize)resistance).EndInit();
        ((System.ComponentModel.ISupportInitialize)interval).EndInit();
        ((System.ComponentModel.ISupportInitialize)resetInterval).EndInit();
        grid.ResumeLayout(false);
        grid.PerformLayout();
        measurementGroup.ResumeLayout(false);
        ResumeLayout(false);
    }

}
